"""update_record

Revision ID: 9e9a41f02114
Revises: 5c48f183c4dc
Create Date: 2025-11-06 20:19:39.592683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e9a41f02114'
down_revision: Union[str, Sequence[str], None] = '5c48f183c4dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diet_records', 'calorie_estimate')
    op.drop_column('diet_records', 'food_description')
    op.drop_column('diet_records', 'ai_analysis')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diet_records', sa.Column('ai_analysis', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('diet_records', sa.Column('food_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('diet_records', sa.Column('calorie_estimate', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
