"""gallery

Revision ID: cdeeeeabfefb
Revises: 9e9a41f02114
Create Date: 2025-11-07 22:04:41.430911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdeeeeabfefb'
down_revision: Union[str, Sequence[str], None] = '9e9a41f02114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('image_base64', sa.Text(), nullable=True),
    sa.Column('analysis_result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_shares_id'), 'gallery_shares', ['id'], unique=False)
    op.create_index(op.f('ix_gallery_shares_user_id'), 'gallery_shares', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gallery_shares_user_id'), table_name='gallery_shares')
    op.drop_index(op.f('ix_gallery_shares_id'), table_name='gallery_shares')
    op.drop_table('gallery_shares')
    # ### end Alembic commands ###
